### ISSUE TITLE
[DOCS] General Functions Page Missing Documentation

### ISSUE THREAD

**Issue by alan-j-lin** [pyjanitor-devs/pyjanitor#862] opened 2021-08-10 17:42 UTC
# Brief Description of Fix

Currently, the docs when you go to the any page under API Documentation displays only the headers for each section. The relevant information for each function has disappeared. Have tried both Chrome and Safari browsers and neither seems to work. It seems that when you go to the website it defaults to the _dev_ branch based on the lower right hand corner?

# Relevant Context

[General Functions](https://pyjanitor.readthedocs.io/reference/general_functions.html#) Screenshot
![screen_view](https://user-images.githubusercontent.com/37027917/128907905-9fc57f87-276d-47f3-a1e0-b6fcbbc2c653.jpg)

[Time Series](https://pyjanitor.readthedocs.io/reference/timeseries.html) Screenshot
![ss_2](https://user-images.githubusercontent.com/37027917/128908405-ba840328-a66e-4162-b2bb-57e01568891d.jpg)

**Comment by samukweku** [comment] 2021-08-11 13:10
@alan-j-lin Thanks for the observation. @loganthomas any ideas?

**Comment by loganthomas** [comment] 2021-08-11 13:16
Thanks for the issue @alan-j-lin! Can you please confirm you are using https://pyjanitor-devs.github.io/pyjanitor for the docs? 

We have recently switched to using GitHub pages instead of the old Read the Docs link.

See #858 for more information.

**Comment by alan-j-lin** [comment] 2021-08-11 13:19
Ah that was it! I was using the old read the docs link. I will add though when you look up pyjanitor on google it still points to the old link so you might want to have it forward to the new one.

**Comment by loganthomas** [comment] 2021-08-11 13:25
Great! Glad that was the root cause. 

Regarding the Google search: that's a great observation. Let me take that back to the dev team. Closing this issue for now.

**Closed as completed** 2021-08-11 13:28 UTC
